const initialValues = ({ loanamount, careertype, captureImg, deductions }) => ({
  loanamount: loanamount,
  careertype: careertype,
  numberofmonth: "",
  loanpurpose: [],
  loanproduct: "",
  other: false,
  otherpurpose: "",
  bvnnumber: "",
  title: "",
  firstname: "",
  lastname: "",
  email: "",
  phonenumber: "",
  dob: "",
  maritalstatus: "",
  noofdependent: "",
  educationlevel: "",
  howdidyouhearaboutus: "",
  houseaddress: "",
  stateofresidence: "",
  lga: "",
  stateoforigin: "",
  ippis: "",
  servicenumber: "",
  valididcard: "",
  idcardnotinclude: false,
  nkinfirstname: "",
  nkinlastname: "",
  nkinphonenumber: "",
  nkinrelationship: "",
  nkinresidentialaddress: "",
  employerId: "",
  otheremployername: "",
  employeraddress: "",
  employmentstartdate: "",
  employmentletter: "",
  netmonthlyincome: "",
  totalannualincome: "",
  officialemail: "",
  uploadpayslip: "",

  // financial information
  salaryaccountname: "",
  salaryaccountnumber: "",
  bankcode: "",
  disbursementbankname: "",
  disbursementaccountnumber: "",
  hasloan: "",
  currentmonthlyplanrepaymentamount: "",
  estimatedmonthlylivingexpense: "",
  buyoverloan: "",
  beneficiaryname: "",
  beneficiarybank: "",
  beneficiaryaccountnumber: "",
  liquidationbalance: "",
  deductions: deductions || "remita",
  guarantee: "",

  // agree & sign
  acceptterms: false,
  acceptpolicy: false,
  sharemyremita: false,
  agreeNibbsDebit: false,
  agreefullname: "",
  agreedate: "",
  signature: "",
  photocapture: captureImg,
  marketerClientPic: "",
  haveagent: "",
  agentcode: "",
  username: "",
  password: "",
  confirmpassword: "",
});

export default initialValues;
